image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - master

build: off

install:

  - java -jar ./artifacts/app-ibank-build-for-testers.jar &
  - chmod +x gradlew

build_script:
  - Dselenide.headless=true, --info
  - ./gradlew test --info